---
- name: Install Remi key
  rpm_key:
    key: "{{ remi_keys[ ansible_distribution_major_version ] }}"
    state: present
  tags:
    - rpm_key
  become: true

- name: Install remi repository
  yum:
    name: "{{ remi_repos[ ansible_distribution_major_version ] }}"
    state: present
  tags:
    - yum
  become: true

- name: Enable requested repositories
  command: "yum config-manager set-enabled {{ repo }}"
  tags:
    - command
  loop: "{{ remi_enable_repos }}"
  loop_control:
    index_var: repo
  become: true
